services:
  - type: web
    name: ippishr-backend
    env: node
    plan: free
    region: ohio 
    buildCommand: |
      npm install
      npx prisma generate
      npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production